### ISSUE TITLE
No borrar posts que cumplan con las normas de la comunidad

### ISSUE THREAD

**Issue by marceloampuerop6** [proinchile/sugerencias#10]
Aunque el tema no guste o ya esté repetido es interesante poder conversar y conocer la opinión de las personas que deseen colaborar dando una respuesta.  Quien considere que el tema es muy repetido simplemente no lo comenta.   Un tema con pocos comentarios da una indicación del poco interés de la comunidad en responder o dar una opinión al respecto.

**Comment by kevinzeladacl** [comment]
Estimado, para esto se ha creado un faq.

https://github.com/programadoreschile/faq

**Comment by marceloampuerop6** [comment]
Ok. Significa que eso que ya no hay más sugerencias? o que las sugerencias debo postearlas en el faq?

**Comment by kevinzeladacl** [comment]
Compadre no se cual es tu objetivo pero por si te costo entender por alguna razón, los temas repetidos se irán a la zona de FAQ :+1:   // editare mi publicación anterior para evitar que se "confundan".
