### ISSUE TITLE
Hacer lista de temas que no desean los administradores

### ISSUE THREAD

**Issue by marceloampuerop6** [proinchile/sugerencias#11]
Para que no nos censuren.

**Comment by kevinzeladacl** [comment]
Aquí están los temas. 

https://github.com/programadoreschile/pautasynormas/blob/master/normas_oficiales.md

**Comment by ginzunza** [comment]
que malote

2015-09-22 14:06 GMT-03:00 Jury <notifications@github.com>:

> Closed #11 <https://github.com/proinchile/sugerencias/issues/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proinchile/sugerencias/issues/11#event-416091909>.
>



-- 
Gustavo Inzunza.
Ingeniero Civil informático.
Universidad Católica de la Santísima Concepción.

Diplomado en Innovación y emprendimiento.
Universidad Católica de Temuco.
