### ISSUE TITLE
Subir a un repositorio publico la página de programadores.cl

### ISSUE THREAD

**Issue by YerkoPalma** [proinchile/sugerencias#12]
Estaba pensando en la posibilidad de que cuando la página www.programadores.cl este terminada sea de manejo publico para la comunidad. Por qué? básicamente para poder agregar funcionalidades sin necesidad de pedírselo a los admins. 

Varios reclaman que no se puede participar, y los admin reclaman que todos reclaman pero hacen poco, entonces si la página, que esta en wordpress, se deja en un repositorio publico, digamos github, se podría fácilmente hacer un pull request cuando se quiera agregar funcionalidad nueva o crear un issue si se trata de una modificación pequeña, que pudiese arreglar cualquiera.

Será posible?

**Comment by kevinzeladacl** [comment]
Yo daré mi opinion personal fuera de ser admin, no me gusta esta idea.

¿Por qué? bueno, partamos con el origen de la páginas web, se espero 1 mes para que enviaran un simple correo lo interesados en participar en su creación, ojo paso unas 2 semanas de discuciónes con "haters" sobre

**Comment by kevinzeladacl** [comment]
Yo daré mi opinión personal fuera de ser admin, no me gusta esta idea.

¿Por qué? bueno, partamos con el origen de la páginas web, se espero 1 mes para que enviaran un simple correo lo interesados en participar en su creación, ojo paso unas 2 semanas de discusiones con "haters" sobre que no podía participar y cuando se abrió todo formal y transparente para que hicieran lo suyo..."desaparecieron". 

Luego de eso se empezó a planificar un trabajo en conjunto como staff para levantar los wordpress (nada del otro mundo) pero con una misión por detrás, con metas de ir avanzando.

La comunidad siempre podrá participar, son el alma de todo esto, pero si alguien tiene ganas de aportar con una funcionalidad nueva puede acercarse al staff y ver su implementación, lo mismo para todo lo "oficial" de la comunidad.

Lo poco que se ha logrado avanzar ha sido por este mecanismo, mucho tiempo el grupo paso sin una dirección clara y no paso nada.

Es mi opinión.

**Comment by YerkoPalma** [comment]
Me parece una opinión valida, pero por ser un tema de la comunidad creo que la misma debiese decidir.

En el peor de los casos tendriamos un repositorio publico que seria mantenido solo por los admins, aún así, me parece más aporte que problema para la comunidad.

Por eso, propongo consultarlo en el grupo.

**Comment by kevinzeladacl** [comment]
Es que la comunidad por si sola no hace nada, se que suena feo pero "la comunidad" exige mucho y da poco, solo por la comunidad, no se hubiera hecho hangout por ejemplo, solo ve el tema de sugerencias, ¿cuantos escriben?,pero en el grupo todos reclaman "censura" por ejemplo, ahora estamos planificando posibles cursos, talleres y eventos que tampoco "la comunidad en si" se encarga. Todo ha sido por el staff.


En todo caso estoy buscando a más gente para unirse al equipo para hacer crecer esto, de hecho una persona para el blog y otra para el grupo en facebook.

**Comment by patrickafv** [comment]
Siempre leo desde afuera , y aqui me gustaria dar mi opinión: 
Es una excelentes idea si son muy bien determinadas las bases y finalidades a seguir de la página. Sin embargo es una mala idea, porque son muchas personas que podrian estaresadas imaginense 800 personas activas modificando , o mejorando un wordpress seria una locura pero no imposible. Entonces, creo yo si se tiene este tipo de debates y que busquen la manera de sierto modo filtrar un poco la gente. Y que se cree una super empresa sin fines de lucro (o como quieran) y todos buscando una misma idea , son puros supuestos,  Saludos.

**Comment by sergioazocar** [comment]
Tomando en cuenta todas las opiniones antes mencionadas, a mi parecer estaría bueno dejarlo público pero con el fin de fixear errores, de todas formas los pull request los admin verán si los aceptan o no...

**Comment by kevinzeladacl** [comment]
Chicos, sorry que interrumpa esto, pero anuncio lo siguiente, porfa vean esto.

https://www.facebook.com/groups/988580631186225/permalink/988587957852159/

Este github pasa a ser de la Futura Asociación Gremial, no del antiguo grupo "Programadores Chile", incluso nos fuimos (ricardo y yo) por querer apoyar temas como estos (aunque estuviera encontra en este caso)
