### ISSUE TITLE
Directorio de grupos "oficiales" regionales

### ISSUE THREAD

**Issue by DMaster69** [proinchile/sugerencias#13]
Crear un directorio de las comunidades "oficiales" de Programadores Chile pero a nivel regional.

**Comment by kevinzeladacl** [comment]
:+1:  Me parece estamos viendo sumar a alguien al github para apoyar estas cosas :100:

**Comment by LuisUrrutia** [comment]
@DMaster69  sinceramente no creo que sea una buena idea crear comunidades a nivel regional, por lo menos dentro de Facebook, ya que la idea es converger, no divergir.
Aunque si se podría hacer algo en la página de programadores.cl.

**Comment by lcjury** [comment]
Se hablara con los otros admins para ver si es posible considerar "comunidades oficiales" las que existen.
