### ISSUE TITLE
Cambiar el logo

### ISSUE THREAD

**Issue by lcjury** [proinchile/sugerencias#14]
No conozco el origen del actual logo de `programadores chile`. Pero si buscan en internet por "rocket flat design ux" encontraran la imagen en varios sitios, ej: http://designmodo.com/flat/. En lo personal me molesta que el logo de la comunidad no sea originario de esta y que solo haya sido una descarga de internet.

Por lo mismo abro este Issue con el fin de conocer la opinión de los usuarios, para saber si vale la pena cambiar o no el logo. Quizás soy el único preocupado por este tema.

**Comment by kevinzeladacl** [comment]
El logo cambiara :) Podemos abrir un desafió o quien se anime puede colocar aquí su propuesta :D
