### ISSUE TITLE
Hashtags de la Comunidad

### ISSUE THREAD

**Issue by hernandemczuk** [proinchile/sugerencias#17]
La principal fuente de tracción que tiene la comunidad es el espacio en Facebook, esto se da porque todos tienen uno y es muy fácil seguir, participar e intervenir en los debates (contrario a tomarse el trabajo de loguearse/registrarse en un foro, ir a la categoria deseada y demás - sin tener en cuenta que es mucho más lenta la navegación - o mismo participar en github - muchas veces por desconocimiento de uso de la herramienta). 

Creo que Facebook nos da esta ventaja para sumar gente rápidamente y crecer exponencialmente, generando un espacio democrático para que todos puedan consultar y/o responder dudas.

Ahora bien, la desventaja claramente es la falta de organización. Recientemente Tao Zamorano subió una post preguntando por el uso de hashtags, el cual es una ideal genial para resolver este problema. Lo que noté, es que muchas veces el buscador del grupo no funciona, pero sí el buscador general de Facebook, por lo que estaría bueno anteponer un hashtag general del grupo antes de cada tema (de forma #PCJavascript, o algo similiar) de forma que podamos hacer uso de la herramienta en todo momento.

Subo este issue para que podamos establecer un orden de jerarquía y todas las variantes posibles (#Tarea, #Consulta, #Proyecto, etc.) para encontrar y organizar la comunidad.

**Comment by lcjury** [comment]
Considero de gran utilidad la búsqueda de facebook por lo mismo. Quizás deberíamos comenzar por generar un listado de los típicos post que se generan en la comunidad, como:

* Preguntas relacionadas a un lenguaje
* Debates generales
* Consultas especificas
  * ¿Que Hosting ocupo?
  * ¿Que IDE ocupo?
* off-topic

Creo que también es importante decidir si: ¿se van a permitir otros tag's en el grupo? ¿Y si un usuario tiene errores gramaticales en los tags (escribir #Rubi en vez de #Ruby)?. Creo que de más está decir que deberíamos discutir la existencia de cada tag, por ej: No creo que sea buena idea tener un tag "#Tarea", ya que podría fomentar preguntas bajo este contexto, cuando el contexto esperado deberia ser algo como: "estoy desarrollando X, he hecho Y y tengo Z error que no se como arreglar" que cabe más bajo un tag asociado a desarrollo en cierto lenguaje/ide.

**Comment by rampmaster** [comment]
Hay que crear un repositorio para normas internas similar a lo de PHP-FIG, deja ver que se puede hacer para ordenar la idea

**Comment by lcjury** [comment]
Se definio en las [normas oficiales]https://github.com/proinchile/pautasynormas/blob/master/normas_oficiales.md) que se deben usar tags para las preguntas de programación.

¿Sera necesario incluir más tags?
