### ISSUE TITLE
Creación de un Foro

### ISSUE THREAD

**Issue by luxpher** [proinchile/sugerencias#2]
Tenía pensado que para mejorar un poco el orden con respecto a Facebook, podríamos hacer un foro que se divida en categorías de interés tales como los distintos lenguajes de programación (más importantes o más usados),  área de SO, incluso incluir un área de distintas regiones para organizarse en eventos de regiones. Lo ideal sería que se agregara a la página oficial de programadores Chile.

**Comment by forres** [comment]
Estaría genial, tienes alguna idea de foro? :o

**Comment by luxpher** [comment]
Si tengo alguna idea en Creacion de foros o en la organizacion?
Porque en creacion si tengo un poco de experiencia, al menos en foros generados automaticos (como foroactivo) pero nada desde 0.
Hace años tenia unos foros de rol pero nada con respecto a esto, aun asi tengo varias ideas de la organizacion de los foros las ire subiendo para ver si se puede hacer. 
Si alguien mas esta de acuerdo seria ideal.

**Comment by luxpher** [comment]
Lo ideal seria instalar PHPBB3 (es el unico que conozco) en el hosting de programadores chile, si es que se puede, si no hacerlo aparte y redireccionarlo.

**Comment by sergioazocar** [comment]
Apoyo la idea, fuí colaborador de un foro hace algunos años y podría ayudar en lo que pueda...

**Comment by kevinzeladacl** [comment]
Chicos ¿Cual sería la diferencia con los varios foros de programación e informática que hay? Yo creo que si se genera una plataforma como evolución del grupo en facebook debería ser algo que nos traiga ventajas reales. 

Saludos.

**Comment by luxpher** [comment]
La diferencia seria que trabajariamos a nivel nacional, incluso se podria hacer a nivel regional.
Sinceramente no conozco foros chilenos de programacion, y si me dices que hay alguno seria interesante integrarnos a ese. Pero en realidad pienso que hace falta un foro.

**Comment by patojimenez** [comment]
Yo tengo algo parecido que hice para la pega, pero es para emprendedodores. Lo bueno que puedes agendar mentorias, tiene el tipico foro y se pueden publicar trabajos, entre otras cosas. Y lo mejor de todo que lo hice como heroku, entonces podemos usarla pa la comunidad oe si. Igual me sirve de feedback. Además tiene una cosa con mapas que muestra la ubicación de las demás personas, obviamente se puede logear con facebook y linkedin

**Comment by sergioazocar** [comment]
La ventaja del foro vs facebook, es el orden de las publicaciones, es más fácil seguir el hilo de un tema y no tener que pinchar "ver comentarios anteriores" que si son muchos no terminas nunca... Aparte de organizar la información por categorías y subcategorías.
Y dejar un espacio para el jugoseo y no desvirtúen los otros temas, digo yo xd

**Comment by luxpher** [comment]
Podria crear un foroactivo para probar y mostrarles una prueba.

**Comment by forres** [comment]
Yo conozco esta opción, node + BB
https://nodebb.org/

Está muy bien posicionada y como somos una comunidad innovadora :sunglasses: 

Lo otro es armar algo como en http://help.noders.com :heart:

**Comment by sergioazocar** [comment]
Puede ser con http://www.simplemachines.org/ igual, es potente y customizable

**Comment by kevinzeladacl** [comment]
Todos estamos de acuerdo con que facebook group tiene el gran defecto del orden de comentarios, pero hay que encontrar algo "pro" que valga la pena implementar, algo que sea más que un simple foro (SMF, PHPBB3,etc.)

@patojimenez se ve interesante lo que comentas, ¿Hay forma de verlo para revisar como funciona? 

Lo otro podría ser que se presenten varias ideas y se someta a una votación durante un tiempo.

saludos.

**Comment by patojimenez** [comment]
Voy a crear una rama para que lo vean :)

**Comment by kevinzeladacl** [comment]
@patojimenez  Excelente ¿Lo vas a subir aquí mismo o en tu github?

**Comment by patojimenez** [comment]
@kevinzeladacl subo la url aquí, para el test.

**Comment by kevinzeladacl** [comment]
@patojimenez  wenisimo :+1:

**Comment by lcjury** [comment]
Cabros, tengo una duda.
Esto se discutió hace un tiempo en el grupo de facebook (Y "CREO" que hubo mucha gente en desacuerdo, yo soy uno de ellos), mi pregunta es, ¿donde esta la gente que estaba en desacuerdo?.

La razón por la que estoy en desacuerdo: ¿creen que la gente se va a meter al foro?, si, es más ordenado, pero es una lata meterse a revisar foros. Facebook significo la muerte de los foros por una razón, no creo que un foro sea la apuesta indicada.

**Comment by cl-ar** [comment]
Creo que un fork de [lobste.rs](https://github.com/jcs/lobsters) no seria mala idea. Mas info sobre la página [aquí](https://lobste.rs/about).
 A mi criterio es mejor que un foro, se puede votar comentarios y publicaciones, responder a comentarios, etiquetas(también filtrar estas), permite generar un lista de correo con las historias nuevas  y mas. Inspirado por Reddit, HackerNews y Slashdot. Creo que tiene mucho mejores herramientas para tratar el contenido y como dicen por ahí el Contenido es Rey.
:heart:

@kevinzeladacl 
@patojimenez

**Comment by sergioazocar** [comment]
o para ser más precisos hacer una especie de stackoverflow chileno, me gusta la idea... puedo ayudar en el frontend y algo con rails (si se hiciera en rails)

**Comment by kevinzeladacl** [comment]
Chicos para todos si quieren crear algo no tienen impedimento, si lo que hacen es bueno y nos sirve como comunidades no tendremos problemas en hacerlo oficial y promocionarlo por todos lados.

No esperen que les digamos "si haganlo" solo vayan y codifiquen :+1: 
x

**Comment by lcjury** [comment]
La discusión queda en Stand-By hasta que alguien desee implementar
